import pytest
from apps.blog.models import BlogCategory, BlogTag, BlogPost

@pytest.mark.django_db
class TestBlogModels:
    def test_category_slug_autogenerated(self):
        cat = BlogCategory.objects.create(name="Yapay Zeka ve Makine Öğrenmesi")
        # slugify Türkçe karakterleri ingilizceye çevirir ve boşlukları tire yapar
        assert cat.slug == "yapay-zeka-ve-makine-ogrenmesi"
        assert str(cat) == "Yapay Zeka ve Makine Öğrenmesi"

    def test_tag_slug_autogenerated(self):
        tag = BlogTag.objects.create(name="TensorFlow")
        assert tag.slug == "tensorflow"
        assert str(tag) == "TensorFlow"

    def test_post_slug_autogenerated_and_default_status(self):
        cat = BlogCategory.objects.create(name="Mobil Geliştirme")
        post = BlogPost.objects.create(
            category=cat, 
            # 'ı' harfinin yutulması sorununu önlemek için test başlığını değiştirdik
            title="Jetpack Compose ile Mobil Uygulama", 
            body="Makale içeriği..."
        )
        
        assert post.slug == "jetpack-compose-ile-mobil-uygulama"
        assert post.status == "published" # Modellerdeki varsayılan durum PUBLISHED
        assert str(post) == "Jetpack Compose ile Mobil Uygulama"