import pytest
from decimal import Decimal
from apps.catalog.models import Category, Brand, Product

@pytest.mark.django_db
class TestCatalogModels:
    def test_category_and_brand_slugs_autogenerated(self):
        cat = Category.objects.create(name="Derin Ogrenme")
        brand = Brand.objects.create(name="NVIDIA Tensor")
        
        assert cat.slug == "derin-ogrenme"
        assert brand.slug == "nvidia-tensor"

    def test_product_effective_price_and_sale_status(self):
        cat = Category.objects.create(name="Donanim")
        
        # İndirimsiz ürün
        product_normal = Product.objects.create(
            category=cat, name="Normal Sunucu", sku="SRV-001", price=Decimal("1000.00")
        )
        assert product_normal.effective_price == Decimal("1000.00")
        assert product_normal.is_on_sale is False

        # İndirimli ürün
        product_sale = Product.objects.create(
            category=cat, name="İndirimli Sunucu", sku="SRV-002", 
            price=Decimal("1000.00"), sale_price=Decimal("800.00")
        )
        assert product_sale.effective_price == Decimal("800.00")
        assert product_sale.is_on_sale is True