from decimal import Decimal

import pytest
from django.urls import reverse

from apps.catalog.models import Category, Product


@pytest.fixture
def category(db):
    return Category.objects.create(name="Eau de Parfum")


@pytest.fixture
def product(db, category):
    return Product.objects.create(
        category=category,
        name="Velvet Rose",
        sku="SKU-001",
        price=Decimal("100.00"),
        sale_price=Decimal("80.00"),
        stock=10,
    )


@pytest.mark.django_db
def test_product_slug_autogenerated(product):
    assert product.slug == "velvet-rose"


@pytest.mark.django_db
def test_effective_price_uses_sale(product):
    assert product.effective_price == Decimal("80.00")
    assert product.is_on_sale is True


@pytest.mark.django_db
def test_product_list_envelope_and_active_only(api_client, product):
    Product.objects.create(
        category=product.category,
        name="Inactive",
        sku="SKU-OFF",
        price=Decimal("50"),
        is_active=False,
    )
    response = api_client.get(reverse("product-list"))
    assert response.status_code == 200
    body = response.json()
    assert "data" in body and "meta" in body
    assert body["meta"]["page"] == 1
    slugs = [p["slug"] for p in body["data"]]
    assert "velvet-rose" in slugs
    assert "inactive" not in slugs
    item = next(p for p in body["data"] if p["slug"] == "velvet-rose")
    assert item["price"] == 80.0
    assert item["originalPrice"] == 100.0
    assert item["available"] == 10
    assert isinstance(item["id"], str)


@pytest.mark.django_db
def test_product_detail_envelope(api_client, product):
    response = api_client.get(reverse("product-detail", args=[product.slug]))
    assert response.status_code == 200
    body = response.json()
    assert "data" in body
    assert body["data"]["slug"] == "velvet-rose"


@pytest.mark.django_db
def test_product_list_sort_param(api_client, category):
    Product.objects.create(category=category, name="Cheap", sku="C", price=Decimal("10"))
    Product.objects.create(category=category, name="Pricey", sku="P", price=Decimal("100"))
    response = api_client.get(reverse("product-list") + "?sort=price_asc")
    prices = [p["price"] for p in response.json()["data"]]
    assert prices == sorted(prices)
