import pytest
from decimal import Decimal
from django.contrib.auth import get_user_model
from apps.catalog.models import Category, Product
from apps.orders.models import Order, OrderItem

User = get_user_model()

@pytest.fixture
def test_user(db):
    return User.objects.create_user(username="dev_user", email="dev@test.local", password="pwd")

@pytest.fixture
def tech_product(db):
    cat = Category.objects.create(name="Yapay Zeka Donanımları")
    return Product.objects.create(category=cat, name="Derin Öğrenme Hızlandırıcı Çip", price=15000.0)

@pytest.mark.django_db
class TestOrderModels:
    def test_order_number_autogenerated(self, test_user):
        order = Order.objects.create(user=test_user, email=test_user.email, full_name="Ahmet Safa")
        
        assert order.number is not None
        assert len(order.number) <= 12
        assert order.number.isupper()

    def test_order_item_line_total(self, test_user, tech_product):
        order = Order.objects.create(user=test_user, email=test_user.email)
        item = OrderItem.objects.create(
            order=order,
            product=tech_product,
            product_name=tech_product.name,
            unit_price=Decimal("15000.00"),
            quantity=2
        )
        assert item.line_total == Decimal("30000.00")

    def test_recalculate_totals(self, test_user, tech_product):
        order = Order.objects.create(user=test_user, email=test_user.email, shipping_fee=Decimal("50.00"))
        
        OrderItem.objects.create(order=order, product=tech_product, product_name="Ürün 1", unit_price=Decimal("100.00"), quantity=2)
        OrderItem.objects.create(order=order, product=tech_product, product_name="Ürün 2", unit_price=Decimal("50.00"), quantity=1)
        
        order.recalculate_totals()
        
        assert order.subtotal == Decimal("250.00") # (100*2) + (50*1)
        assert order.total == Decimal("300.00")    # Subtotal + 50 Shipping