# Generated by Django 5.0.6 on 2026-05-09 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(blank=True, default="", max_length=120)),
                ("title", models.CharField(max_length=200)),
                ("background_image", models.CharField(max_length=255)),
                ("cta_label", models.CharField(default="Shop now", max_length=80)),
                ("cta_href", models.CharField(default="/shop", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banner",
            },
        ),
        migrations.CreateModel(
            name="FeaturedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(blank=True, default="", max_length=120)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("image_src", models.CharField(max_length=255)),
                ("image_alt", models.CharField(blank=True, default="", max_length=200)),
                ("cta_href", models.CharField(default="/shop", max_length=255)),
                ("image_right", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bg",
                    models.CharField(
                        help_text="Background image URL or path", max_length=255
                    ),
                ),
                ("eyebrow", models.CharField(blank=True, default="", max_length=120)),
                ("title", models.CharField(max_length=200)),
                (
                    "title_span",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("body", models.TextField(blank=True, default="")),
                ("cta_label", models.CharField(default="Shop now", max_length=80)),
                ("cta_href", models.CharField(default="/shop", max_length=255)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="BannerFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon identifier or asset path", max_length=80
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "banner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="home.banner",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
    ]
