# Generated by Django 5.0.6 on 2026-05-16 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_color_size_tag_theme_vendor_product_colors_and_more"),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={"verbose_name": "Banner", "verbose_name_plural": "Banners"},
        ),
        migrations.AddField(
            model_name="banner",
            name="theme",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banner",
                to="catalog.theme",
            ),
        ),
        migrations.AddField(
            model_name="featuredproduct",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="featured_products",
                to="catalog.theme",
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hero_slides",
                to="catalog.theme",
            ),
        ),
    ]
