# Generated by Django 5.0.6 on 2026-05-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="cover_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External or static path to the cover image.",
                max_length=255,
            ),
        ),
    ]
