# Generated by Django 5.0.6 on 2026-05-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External or static path to a primary image (e.g. /images/product1.webp).",
                max_length=255,
            ),
        ),
    ]
