# Generated by Django 5.0.6 on 2026-05-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_color_size_tag_theme_vendor_product_colors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("theme", "name")},
        ),
    ]
